apiVersion : apps/v1
kind: Deployment
metadata:
  name: guidetour 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guidetour
  template:
    metadata:
      labels:
        app: guidetour 
    spec:
      containers:
        - name: guidetour 
          image: unlockokrregistryprod.azurecr.io/guidetour
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
            value: "true"